PLANETS = (
    "Alderaan",
    "Yavin IV",
    "Hoth",
    "Dagobah",
    "Bespin",
    "Endor",
    "Naboo",
    "Coruscant",
    "Kamino",
    "Geonosis",
    "Utapau",
    "Mustafar",
    "Kashyyyk",
    "Polis Massa",
    "Mygeeto",
    "Felucia",
    "Cato Neimoidia",
    "Saleucami",
    "Stewjon",
    "Eriadu",
    "Corellia",
    "Rodia",
    "Nal Hutta",
    "Dantooine",
    "Bestine IV",
    "Ord Mantell",
    "unknown",
    "Trandosha",
    "Socorro",
    "Mon Cala",
    "Chandrila",
    "Sullust",
    "Toydaria",
    "Malastare",
    "Dathomir",
    "Ryloth",
    "Aleen Minor",
    "Vulpter",
    "Troiken",
    "Tund",
    "Haruun Kal",
    "Cerea",
    "Glee Anselm",
    "Iridonia",
    "Tholoth",
    "Iktotch",
    "Quermia",
    "Dorin",
    "Champala",
    "Mirial",
    "Serenno",
    "Concord Dawn",
    "Zolan",
    "Ojom",
    "Skako",
    "Muunilinst",
    "Shili",
    "Kalee",
    "Umbara",
    "Tatooine",
    "Jakku",
)
