
STARSHIPS = (
    "Executor",
    "Sentinel-Class Landing Craft",
    "Death Star",
    "Millennium Falcon",
    "Y-Wing",
    "X-Wing",
    "Tie Advanced X1",
    "Slave 1",
    "Imperial Shuttle",
    "Ef76 Nebulon-B Escort Frigate",
    "Calamari Cruiser",
    "A-Wing",
    "B-Wing",
    "Republic Cruiser",
    "Naboo Fighter",
    "Naboo Royal Starship",
    "Scimitar",
    "J-Type Diplomatic Barge",
    "Aa-9 Coruscant Freighter",
    "Jedi Starfighter",
    "H-Type Nubian Yacht",
    "Star Destroyer",
    "Trade Federation Cruiser",
    "Theta-Class T-2C Shuttle",
    "T-70 X-Wing Fighter",
    "Rebel Transport",
    "Droid Control Ship",
    "Republic Assault Ship",
    "Solar Sailer",
    "Republic Attack Cruiser",
    "Naboo Star Skiff",
    "Jedi Interceptor",
    "Arc-170",
    "Belbullab-22 Starfighter",
    "V-Wing",
    "Cr90 Corvette",
    "Banking Clan Frigate",
)
