
VEHICLES = (
    "Sand Crawler",
    "T-16 Skyhopper",
    "X-34 Landspeeder",
    "Tie/Ln Starfighter",
    "Snowspeeder",
    "Tie Bomber",
    "AT-AT",
    "AT-ST",
    "Storm Iv Twin-Pod Cloud Car",
    "Sail Barge",
    "Bantha-Ii Cargo Skiff",
    "Tie/In Interceptor",
    "Imperial Speeder Bike",
    "Vulture Droid",
    "Multi-Troop Transport",
    "Armored Assault Tank",
    "Single Trooper Aerial Platform",
    "C-9979 Landing Craft",
    "Tribubble Bongo",
    "Sith Speeder",
    "Zephyr-G Swoop Bike",
    "Koro-2 Exodrive Airspeeder",
    "Xj-6 Airspeeder",
    "Laat/I",
    "Laat/C",
    "Tsmeu-6 Personal Wheel Bike",
    "Emergency Firespeeder",
    "Droid Tri-Fighter",
    "Oevvaor Jet Catamaran",
    "Raddaugh Gnasp Fluttercraft",
    "Clone Turbo Tank",
    "Corporate Alliance Tank Droid",
    "Droid Gunship",
    "AT-RT",
    "AT-TE",
    "Spha",
    "Flitknot Speeder",
    "Neimoidian Shuttle",
    "Geonosian Starfighter",
)
